const sampleListings = [
  {
    title: "Cozy Beachfront Cottage",
    description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg",
    },
    price: 1500,
    location: "Malibu",
    country: "United States",
  },
  {
    title: "Modern Loft in Downtown",
    description: "Stay in the heart of the city in this stylish loft apartment. Perfect for urban explorers!",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
    },
    price: 1200,
    location: "New York City",
    country: "United States",
  },
  {
    title: "Mountain Retreat",
    description: "Unplug and unwind in this peaceful mountain cabin. Surrounded by nature, it's a perfect place to recharge.",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
    },
    price: 1000,
    location: "Aspen",
    country: "United States",
  },
  {
    title: "Historic Villa in Tuscany",
    description: "Experience the charm of Tuscany in this beautifully restored villa.",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
    },
    price: 2500,
    location: "Florence",
    country: "Italy",
  },
  {
    title: "Secluded Treehouse Getaway",
    description: "Live among the treetops in this unique treehouse retreat.",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/247663/pexels-photo-247663.jpeg",
    },
    price: 800,
    location: "Portland",
    country: "United States",
  },
  {
    title: "Beachfront Paradise",
    description: "Step out of your door onto the sandy beach.",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg",
    },
    price: 2000,
    location: "Cancun",
    country: "Mexico",
  },
  {
    title: "Rustic Cabin by the Lake",
    description: "Spend your days fishing and kayaking on the serene lake.",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg",
    },
    price: 900,
    location: "Lake Tahoe",
    country: "United States",
  },
  {
    title: "Luxury Penthouse with City Views",
    description: "Indulge in luxury living with panoramic city views.",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
    },
    price: 3500,
    location: "Los Angeles",
    country: "United States",
  },
  {
    title: "Ski-In/Ski-Out Chalet",
    description: "Hit the slopes right from your doorstep.",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/754268/pexels-photo-754268.jpeg",
    },
    price: 3000,
    location: "Verbier",
    country: "Switzerland",
  },
  {
    title: "Safari Lodge in the Serengeti",
    description: "Experience the thrill of the wild.",
    image: {
      filename: "listingimage",
      url: "https://images.pexels.com/photos/667205/pexels-photo-667205.jpeg",
    },
    price: 4000,
    location: "Serengeti National Park",
    country: "Tanzania",
  },
  {
  title: "Glass Igloo in Lapland",
  description: "Sleep under the northern lights in this magical glass igloo experience.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/754263/pexels-photo-754263.jpeg",
  },
  price: 4500,
  location: "Lapland",
  country: "Finland",
},
{
  title: "Overwater Villa in Bora Bora",
  description: "Luxury villa above crystal-clear turquoise water with private deck.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/1287460/pexels-photo-1287460.jpeg",
  },
  price: 8000,
  location: "Bora Bora",
  country: "French Polynesia",
},
{
  title: "Desert Camp in Sahara",
  description: "Experience golden dunes and starry nights in a luxury desert camp.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/248771/pexels-photo-248771.jpeg",
  },
  price: 2000,
  location: "Sahara",
  country: "Morocco",
},
{
  title: "Santorini Cave House",
  description: "Stay in a stunning white cave house overlooking the Aegean Sea.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg",
  },
  price: 3500,
  location: "Santorini",
  country: "Greece",
},
{
  title: "Tokyo Capsule Stay",
  description: "Unique compact living experience in the heart of Tokyo.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/261395/pexels-photo-261395.jpeg",
  },
  price: 900,
  location: "Tokyo",
  country: "Japan",
},
{
  title: "Swiss Alps Wooden Chalet",
  description: "Cozy wooden chalet surrounded by snowy mountains.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/754268/pexels-photo-754268.jpeg",
  },
  price: 4200,
  location: "Zermatt",
  country: "Switzerland",
},
{
  title: "Luxury Houseboat in Amsterdam",
  description: "Stay on water in a stylish floating home with canal views.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
  },
  price: 2300,
  location: "Amsterdam",
  country: "Netherlands",
},
{
  title: "Jungle Eco Lodge in Amazon",
  description: "Reconnect with nature in a sustainable jungle lodge.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/247663/pexels-photo-247663.jpeg",
  },
  price: 1800,
  location: "Amazon",
  country: "Brazil",
},
{
  title: "Cliff Hanging Hotel in Peru",
  description: "Sleep inside a glass pod hanging off a mountain cliff.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
  },
  price: 5000,
  location: "Cusco",
  country: "Peru",
},
{
  title: "Beach Shack in Goa",
  description: "Simple and chill beachside stay with sunset views.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg",
  },
  price: 1200,
  location: "Goa",
  country: "India",
},
{
  title: "Himalayan Wooden Cabin",
  description: "Peaceful cabin with breathtaking mountain views.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/2102587/pexels-photo-2102587.jpeg",
  },
  price: 1500,
  location: "Manali",
  country: "India",
},
{
  title: "Dubai Sky Luxury Apartment",
  description: "High-rise luxury apartment with skyline views.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
  },
  price: 6000,
  location: "Dubai",
  country: "UAE",
},
{
  title: "Paris Romantic Studio",
  description: "Cute studio apartment near Eiffel Tower.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
  },
  price: 2200,
  location: "Paris",
  country: "France",
},
{
  title: "Iceland Volcano View Cabin",
  description: "Stay near lava fields with dramatic landscapes.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg",
  },
  price: 3800,
  location: "Reykjavik",
  country: "Iceland",
},
{
  title: "New Zealand Lake House",
  description: "Beautiful lakeside house with scenic mountain views.",
  image: {
    filename: "listingimage",
    url: "https://images.pexels.com/photos/261102/pexels-photo-261102.jpeg",
  },
  price: 2700,
  location: "Queenstown",
  country: "New Zealand",
}
];
module.exports = { data: sampleListings };